# Generated by Django 4.2.16 on 2024-12-14 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product_item',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.TextField()),
                ('product_keyword', models.TextField()),
                ('category', models.TextField()),
                ('specification', models.TextField()),
                ('price', models.IntegerField()),
                ('link', models.TextField()),
                ('fromwhich', models.CharField(default='none', max_length=10)),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='product_keyword',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword_name', models.TextField()),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('minPrice', models.IntegerField()),
                ('maxPrice', models.IntegerField()),
                ('TBavgPrice', models.FloatField()),
                ('JDavgPrice', models.FloatField()),
                ('TBcount', models.IntegerField()),
                ('JDcount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tb_token', models.TextField(blank=True, null=True)),
                ('user_jd_token', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='collect_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_keyword', models.TextField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
