# Generated by Django 4.2.16 on 2024-12-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect_record',
            name='need_notify',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
