# Generated by Django 4.2.16 on 2024-12-14 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbj', '0002_collect_record_need_notify'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_keyword_general',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.TextField()),
                ('lowest', models.IntegerField()),
                ('latest_keyword_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbj.product_keyword')),
                ('minPriceItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbj.product_item')),
            ],
        ),
    ]
