# Generated by Django 4.2.16 on 2024-12-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbj', '0003_product_keyword_general'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_keyword_general',
            name='minPriceItem',
        ),
    ]
