# Generated by Django 4.2.16 on 2024-12-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbj', '0004_remove_product_keyword_general_minpriceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_keyword_general',
            name='lowest_link',
            field=models.TextField(default='//www.taobao.com'),
            preserve_default=False,
        ),
    ]
